#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
chmod +x "$install_dir/cjdroute"

#=================================================
# CONFIGURING CJDNS
#=================================================
ynh_script_progression "Configuring $app..."

$install_dir/cjdroute --genconf | $install_dir/cjdroute --cleanconf > $install_dir/cjdroute.conf

jq '.security[0].setuser = 0' $install_dir/cjdroute.conf > $install_dir/cjdroute.conf.tmp && mv $install_dir/cjdroute.conf.tmp $install_dir/cjdroute.conf
jq '.security[0].seccomp = 0' $install_dir/cjdroute.conf > $install_dir/cjdroute.conf.tmp && mv $install_dir/cjdroute.conf.tmp $install_dir/cjdroute.conf
jq '.noBackground = 1' $install_dir/cjdroute.conf > $install_dir/cjdroute.conf.tmp && mv $install_dir/cjdroute.conf.tmp $install_dir/cjdroute.conf

#=================================================
# UPGRADE PEERS
#=================================================
ynh_script_progression "Getting $app peers..."

# Fetch the JSON data
json=$(curl -s -A "ynh" https://vpn.anode.co/api/0.4/vpn/cjdns/peeringlines/)
echo "Got peering lines"

length=$(echo $json | jq '. | length')
ynh_script_progression "Adding $length $app peers..."
for (( i=0; i<$length; i++ ))
do
    # Parse the JSON data
    ip=$(echo $json | jq -r --argjson i $i '.[$i].ip')
    port=$(echo $json | jq -r --argjson i $i '.[$i].port')
    login=$(echo $json | jq -r --argjson i $i '.[$i].login')
    password=$(echo $json | jq -r --argjson i $i '.[$i].password')
    publicKey=$(echo $json | jq -r --argjson i $i '.[$i].publicKey')

    # Prepare the peer to be inserted
    peer=$(jq -n \
    --arg ip_port "$ip:$port" \
    --arg login "$login" \
    --arg password "$password" \
    --arg publicKey "$publicKey" \
    '{($ip_port): {"login": $login, "password": $password, "publicKey": $publicKey}}')

    # Insert the peer into the cjdroute.conf file
    jq --argjson peer "$peer" '(.interfaces.UDPInterface[] | select(.beaconPort == 64512) .connectTo) |= . + $peer' $install_dir/cjdroute.conf > $install_dir/cjdroute.conf.tmp

    mv $install_dir/cjdroute.conf.tmp $install_dir/cjdroute.conf
done

cjdns_ipv6=$(jq -r '.ipv6' < $install_dir/cjdroute.conf)
ynh_app_setting_set --key=cjdns_ipv6 --value=$cjdns_ipv6

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Encrypted IPv6 network" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
